name: Deque

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake, GTest and cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgtest-dev cppcheck
          sudo ln -s /usr/include/gtest /usr/include/gmock

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Running main tests
        run: |
          ./build/main_tests

      - name: Running stress tests
        run: |
          ./build/stress_tests

      - name: Static Code Analysis(cppcheck)
        run: |
          cd build
          cppcheck --enable=all --std=c++17 ..